# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taw.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttaw.proto\x12\x03taw\"\x9b\x01\n\x06Script\x12\r\n\x05label\x18\x01 \x01(\t\x12\x1e\n\x04\x63ode\x18\x04 \x01(\x0b\x32\x10.taw.Script.Code\x1a\x46\n\x04\x43ode\x12\x0e\n\x06script\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32\x16.taw.Script.ScriptType:\x08NATIVEPY\"\x1a\n\nScriptType\x12\x0c\n\x08NATIVEPY\x10\x00\"d\n\x05World\x12$\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x12.taw.World.Command\x1a\x35\n\x07\x43ommand\x12\x0f\n\x07\x61liases\x18\x01 \x03(\t\x12\x19\n\x04\x63ode\x18\x02 \x01(\x0b\x32\x0b.taw.Script')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taw_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SCRIPT']._serialized_start=19
  _globals['_SCRIPT']._serialized_end=174
  _globals['_SCRIPT_CODE']._serialized_start=76
  _globals['_SCRIPT_CODE']._serialized_end=146
  _globals['_SCRIPT_SCRIPTTYPE']._serialized_start=148
  _globals['_SCRIPT_SCRIPTTYPE']._serialized_end=174
  _globals['_WORLD']._serialized_start=176
  _globals['_WORLD']._serialized_end=276
  _globals['_WORLD_COMMAND']._serialized_start=223
  _globals['_WORLD_COMMAND']._serialized_end=276
# @@protoc_insertion_point(module_scope)
