# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: taw.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .google import protobuf


class Direction(betterproto.Enum):
    NORTH = 0
    SOUTH = 1
    EAST = 2
    WEST = 3
    UP = 4
    DOWN = 5


class ScriptScriptType(betterproto.Enum):
    NATIVE_PY = 0


@dataclass
class Dict(betterproto.Message):
    keys: List[str] = betterproto.string_field(1)
    values: List[bytes] = betterproto.bytes_field(2)


@dataclass
class BoolDict(betterproto.Message):
    keys: List[str] = betterproto.string_field(1)
    values: List[bool] = betterproto.bool_field(2)


@dataclass
class Script(betterproto.Message):
    label: str = betterproto.string_field(1)
    code: "ScriptCode" = betterproto.message_field(4)


@dataclass
class ScriptCode(betterproto.Message):
    script: str = betterproto.string_field(1)
    type: "ScriptScriptType" = betterproto.enum_field(2)


@dataclass
class Room(betterproto.Message):
    name: str = betterproto.string_field(1)
    iname: str = betterproto.string_field(2)
    desc: str = betterproto.string_field(3)
    exits: List["Room"] = betterproto.message_field(4)
    items: List["Object"] = betterproto.message_field(5)


@dataclass
class Object(betterproto.Message):
    name: str = betterproto.string_field(1)
    sdesc: str = betterproto.string_field(2)
    ldesc: str = betterproto.string_field(3)
    loc: "Room" = betterproto.message_field(4)
    iname: str = betterproto.string_field(5)
    flags: "BoolDict" = betterproto.message_field(6)


@dataclass
class Item(betterproto.Message):
    name: str = betterproto.string_field(1)
    sdesc: str = betterproto.string_field(2)
    ldesc: str = betterproto.string_field(3)
    loc: "Room" = betterproto.message_field(4)
    iname: str = betterproto.string_field(5)
    flags: "BoolDict" = betterproto.message_field(6)


@dataclass
class World(betterproto.Message):
    commands: List["WorldCommand"] = betterproto.message_field(1)
    room: "Room" = betterproto.message_field(2)


@dataclass
class WorldCommand(betterproto.Message):
    aliases: List[str] = betterproto.string_field(1)
    code: "Script" = betterproto.message_field(2)


@dataclass
class Save(betterproto.Message):
    world: "World" = betterproto.message_field(1)
    saves: "Dict" = betterproto.message_field(2)


@dataclass
class Player(betterproto.Message):
    name: str = betterproto.string_field(1)
    loc: "Room" = betterproto.message_field(2)
    inventory: "Room" = betterproto.message_field(3)
    colored: bool = betterproto.bool_field(4)


@dataclass
class Entity(betterproto.Message):
    name: str = betterproto.string_field(1)
    loc: "Room" = betterproto.message_field(2)
    inventory: "Room" = betterproto.message_field(3)


@dataclass
class Event(betterproto.Message):
    target: List[protobuf.Any] = betterproto.message_field(1)
    action: List[protobuf.Any] = betterproto.message_field(2)


@dataclass
class MovePlayerEvent(betterproto.Message):
    target: "Player" = betterproto.message_field(1)
    to: "Room" = betterproto.message_field(2)


@dataclass
class MoveObjectEvent(betterproto.Message):
    target: "Object" = betterproto.message_field(1)
    to: "Room" = betterproto.message_field(2)


@dataclass
class MoveItemEvent(betterproto.Message):
    target: "Item" = betterproto.message_field(1)
    to: "Room" = betterproto.message_field(2)


@dataclass
class AddExitEvent(betterproto.Message):
    target: "Room" = betterproto.message_field(1)
    dir: "Direction" = betterproto.enum_field(2)
    to: "Room" = betterproto.message_field(3)


@dataclass
class LocalChatEvent(betterproto.Message):
    source: "Room" = betterproto.message_field(1)
    mess: str = betterproto.string_field(2)


@dataclass
class GlobalChatEvent(betterproto.Message):
    mess: str = betterproto.string_field(1)
